#!/usr/bin/ruby

#	 Copyright 2010 by Nathaniel Sherry
#
#    This file is part of TVify.
#
#    TVify is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    TVify is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with TVify.  If not, see <http://www.gnu.org/licenses/>.


if ARGV[0] == "?" 

	puts "[TEST RUN] Generates a hash file for the video files in the current directory and places the hash file in the hash archive folder specified in the config file."
	exit 0
	
end

require File.dirname(__FILE__)+'/indexer-functions.rb'


puts `indexer.rb --target-folder="#{defaultTarget}" --hash-only --simulate`
